//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFixWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestQuotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestQuotation()
        {
            this.Quotations = new HashSet<Quotation>();
        }
    
        public int RequestQuotationID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotations { get; set; }
    }
}
